apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
   - port: 3000
     targetPort: 3000
     protocol: TCP
