apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: abelovn
    name: web
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http # one of the major thing w/o it you could not have active targets in Prometheus
  selector:
    app: abelovn
    name: web