apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-data
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: cicd
  labels:
    app: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      initContainers:
      - name: init
        image: busybox:latest
        command: ['/bin/chown', '200:200', '/sonar-data']
        volumeMounts:
        - name: sonar-data
          mountPath: /sonar-data
      containers:
      - image: sonarqube:7.9.4-community
        name: sonar
        volumeMounts:
        - name: sonar-data
          mountPath: /sonar-data
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data

---
apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: cicd
spec:
  type: LoadBalancer
  selector:
    app: sonar
  ports:
  - name: ui
    protocol: TCP
    port: 9000
    targetPort: 9000
