apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abelovn
  template:
    metadata:
      labels:
        app: abelovn
        name: web
        namespace: production
    spec:
      containers:
      - name: web
        image: abelovn/my_registry_prod:latest
        env:
        - name: connection_str
          valueFrom: 
            secretKeyRef:
              name: secrets
              key: connection_str
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 400m
       
        imagePullPolicy: Always
