apiVersion: v1
kind: Service
metadata:
  name: kb
  labels:
    name: kb
spec:
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  type: NodePort
  ports:
   - port: 5601
     targetPort: 5601
     protocol: TCP

