name: test
      
# Controls when the action will run. 
on:
  # Triggers the workflow on push to dev
  push:
    branches-ignore: [ main ]
    
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    env:
      MENV : feature-smoketest
      IMGNAME: abelovn/my_registry
    steps:
      - uses: actions/checkout@v2
      # - name: Smoke test
      #   run: python3 ./smoketest.py 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pip install requests
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python smoketest.py

      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      