name: test
      
# Controls when the action will run. 
on:
  # Triggers the workflow on push to dev
  push:
    branches-ignore: [ main ]
    
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    env:
      MENV : feature-smoketest
      IMGNAME: abelovn/my_registry
    steps:
      - uses: actions/checkout@v2
      # - name: Smoke test
      #   run: python3 ./smoketest.py 
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python ./smoketest.py

      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      